// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: user_jobs.sql

package database

import (
	"context"
)

const upsertUserJob = `-- name: UpsertUserJob :exec
insert into user_jobs (
    user_id,
    job_id,
    feedback
) values (
    $1,
    $2,
    $3
) on conflict (user_id, job_id) do update set
    feedback = $3,
    updated_at = now()
`

type UpsertUserJobParams struct {
	UserID   int64           `json:"user_id"`
	JobID    string          `json:"job_id"`
	Feedback UserJobFeedback `json:"feedback"`
}

func (q *Queries) UpsertUserJob(ctx context.Context, arg UpsertUserJobParams) error {
	_, err := q.db.Exec(ctx, upsertUserJob, arg.UserID, arg.JobID, arg.Feedback)
	return err
}
