// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"time"
)

type Job struct {
	CreatedAt   time.Time  `json:"created_at"`
	ID          string     `json:"id"`
	Source      string     `json:"source"`
	PublishedAt *time.Time `json:"published_at"`
	Link        string     `json:"link"`
	Title       string     `json:"title"`
	Description string     `json:"description"`
	CompanyAI   string     `json:"ai_company"`
	RoleAI      string     `json:"ai_role"`
	SeniorityAI string     `json:"ai_seniority"`
	OverviewAI  string     `json:"ai_overview"`
	HashtagsAI  []string   `json:"ai_hashtags"`
}
