// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
)

type Querier interface {
	InsertJob(ctx context.Context, arg InsertJobParams) error
	JobsExist(ctx context.Context, ids []string) ([]string, error)
}

var _ Querier = (*Queries)(nil)
